# Generated by Django 5.2 on 2025-06-06 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disiplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('foto', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='experto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='regla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=150)),
                ('detalle', models.CharField(max_length=150)),
                ('norma_establecida', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_certificacion', models.CharField(max_length=150)),
                ('fecha_emision', models.DateField()),
                ('experto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificacion', to='ejercicios.experto')),
            ],
        ),
        migrations.CreateModel(
            name='tipoCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('detalle', models.CharField(max_length=150)),
                ('estilo', models.CharField(max_length=150)),
                ('distancia', models.CharField(max_length=150)),
                ('tiempo', models.CharField(max_length=150)),
                ('disiplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_competencia', to='ejercicios.disiplina')),
                ('recomendaciones', models.ManyToManyField(related_name='tipos_competencia_asociadas', to='ejercicios.recomendacion')),
                ('reglas', models.ManyToManyField(related_name='tipos_competencia', to='ejercicios.regla')),
            ],
        ),
    ]
